### ISSUE TITLE
Mobile optimization.

### ISSUE THREAD

**Issue by thekerp** [lexDAO/LexDAO-LandingV2#14]

**Comment by konstantinbrazhnik** [comment]
@thekerp What specifically do you want to optimize. The header image was stacked just for very small screens, but everything else is pretty responsive.

**Comment by thekerp** [comment]
Cool. @maxgrok had mentioned there was a bit to do, so was flagging it here. But nothing too fancy, just want it to be useable.

Mobile traffic is climbing now that wallet deep linking works. 🚀
